// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addGameParticipant = `-- name: AddGameParticipant :exec
INSERT INTO game_participants (game_id, user_id, placement)
VALUES (?, ?, ?)
`

type AddGameParticipantParams struct {
	GameID    string
	UserID    string
	Placement int64
}

func (q *Queries) AddGameParticipant(ctx context.Context, arg AddGameParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addGameParticipant, arg.GameID, arg.UserID, arg.Placement)
	return err
}

const createGame = `-- name: CreateGame :exec
INSERT INTO games (id, started_at, game_mode)
VALUES (?, ?, ?)
`

type CreateGameParams struct {
	ID        string
	StartedAt time.Time
	GameMode  sql.NullString
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) error {
	_, err := q.db.ExecContext(ctx, createGame, arg.ID, arg.StartedAt, arg.GameMode)
	return err
}

const getMatchHistoryForUser = `-- name: GetMatchHistoryForUser :many
SELECT
    gp.game_id,
    g.started_at,
    g.game_mode,
    gp.placement
FROM game_participants gp
JOIN games g ON g.id = gp.game_id
WHERE gp.user_id = ?
ORDER BY g.started_at DESC
LIMIT ?
`

type GetMatchHistoryForUserParams struct {
	UserID string
	Limit  int64
}

type GetMatchHistoryForUserRow struct {
	GameID    string
	StartedAt time.Time
	GameMode  sql.NullString
	Placement int64
}

func (q *Queries) GetMatchHistoryForUser(ctx context.Context, arg GetMatchHistoryForUserParams) ([]GetMatchHistoryForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getMatchHistoryForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchHistoryForUserRow
	for rows.Next() {
		var i GetMatchHistoryForUserRow
		if err := rows.Scan(
			&i.GameID,
			&i.StartedAt,
			&i.GameMode,
			&i.Placement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
