// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type User struct {
	Username       string
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
