// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Game struct {
	ID        string
	StartedAt time.Time
	GameMode  sql.NullString
}

type GameParticipant struct {
	GameID    string
	UserID    string
	Placement int64
}

type User struct {
	Username       string
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
