// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type User struct {
	ID             string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Email          string
	HashedPassword string
}
