// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_stats.sql

package database

import (
	"context"
)

const createUserStats = `-- name: CreateUserStats :exec
INSERT INTO user_stats (user_id)
VALUES (?)
`

func (q *Queries) CreateUserStats(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, createUserStats, userID)
	return err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    COUNT(*) AS total_games,
    COUNT(*) FILTER (WHERE placement = 1) AS wins,
    COUNT(*) FILTER (WHERE placement != 1) AS losses
FROM game_participants
WHERE user_id = ?
`

type GetUserStatsRow struct {
	TotalGames int64
	Wins       int64
	Losses     int64
}

func (q *Queries) GetUserStats(ctx context.Context, userID string) (GetUserStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(&i.TotalGames, &i.Wins, &i.Losses)
	return i, err
}
